Linux: Merge tag 'v3.10.105'
This is the 3.10.105 stable release

* tag 'v3.10.105' (315 commits):
  Linux 3.10.105
  metag: Only define atomic_dec_if_positive conditionally
  fbdev/efifb: Fix 16 color palette entry calculation
  dm: mark request_queue dead before destroying the DM device
  regulator: tps65910: Work around silicon erratum SWCZ010
  ASoC: omap-mcpdm: Fix irq resource handling
  mfd: 88pm80x: Double shifting bug in suspend/resume
  mpi: Fix NULL ptr dereference in mpi_powm() [ver #3]
  hwmon: (adt7411) set bit 3 in CFG1 register
  can: dev: fix deadlock reported after bus-off
  mm,ksm: fix endless looping in allocating memory when ksm enable
  dm flakey: fix reads to be issued if drop_writes configured
  tile: avoid using clocksource_cyc2ns with absolute cycle count
  PCI: Handle read-only BARs on AMD CS553x devices
  ACPI / APEI: Fix incorrect return value of ghes_proc()
  mei: bus: fix received data size check in NFC fixup
  staging: iio: ad5933: avoid uninitialized variable in error case
  hv: do not lose pending heartbeat vmbus packets
  KEYS: Fix short sprintf buffer in /proc/keys show function
  uio: fix dmem_region_start computation
  gpio: mpc8xxx: Correct irq handler function
  cx231xx: fix GPIOs for Pixelview SBTVD hybrid
  cx231xx: don't return error on success
  mb86a20s: fix demod settings
  mb86a20s: fix the locking logic
  pstore/ram: Use memcpy_fromio() to save old buffer
  pstore/ram: Use memcpy_toio instead of memcpy
  pstore/core: drop cmpxchg based updates
  mmc: block: don't use CMD23 with very old MMC cards
  mmc: mxs: Initialize the spinlock prior to using it
  PM / sleep: fix device reference leak in test_suspend
  mfd: core: Fix device reference leak in mfd_clone_cell
  ratelimit: fix bug in time interval by resetting right begin time
  rcu: Fix soft lockup for rcu_nocb_kthread
  tools/vm/slabinfo: fix an unintentional printf
  lib/genalloc.c: start search from start of chunk
  drbd: Fix kernel_sendmsg() usage - potential NULL deref
  cfq: fix starvation of asynchronous writes
  Revert "ipc/sem.c: optimize sem_lock()"
  kernel/fork: fix CLONE_CHILD_CLEARTID regression in nscd
  tracing: Move mutex to protect against resetting of seq data
  kaweth: fix firmware download
  net: sky2: Fix shutdown crash
  ipv4: Set skb->protocol properly for local output
  mwifiex: printk() overflow with 32-byte SSIDs
  cfg80211: limit scan results cache size
  mac80211: discard multicast and 4-addr A-MSDUs
  mac80211: fix purging multicast PS buffer queue
  ipv4: use new_gw for redirect neigh lookup
  neigh: check error pointer instead of NULL for ipv4_neigh_lookup()
  sctp: assign assoc_id earlier in __sctp_connect
  dccp: fix out of bound access in dccp_v4_err()
  dccp: do not send reset to already closed sockets
  net: mangle zero checksum in skb_checksum_help()
  net: clear sk_err_soft in sk_clone_lock()
  sctp: validate chunk len before actually using it
  net: sctp, forbid negative length
  packet: call fanout_release, while UNREGISTERING a netdev
  ipmr, ip6mr: fix scheduling while atomic and a deadlock with ipmr_get_route
  net: avoid sk_forward_alloc overflows
  net: fix sk_mem_reclaim_partial()
  can: bcm: fix warning in bcm_connect/proc_register
  netfilter: fix namespace handling in nf_log_proc_dostring
  firewire: net: fix fragmented datagram_size off-by-one
  firewire: net: guard against rx buffer overflows
  net/mlx4_core: Allow resetting VF admin mac to zero
  pstore: Fix buffer overflow while write offset equal to buffer size
  brcmfmac: avoid potential stack overflow in brcmf_cfg80211_start_ap()
  brcmsmac: Initialize power in brcms_c_stf_ss_algo_channel_get()
  brcmsmac: Free packet if dma_mapping_error() fails in dma_rxfill
  svc: Avoid garbage replies when pc_func() returns rpc_drop_reply
  iwlwifi: pcie: fix access to scratch buffer
  ipvs: count pre-established TCP states as active
  net: disable fragment reassembly if high_thresh is set to zero
  mISDN: Fixing missing validation in base_sock_bind()
  mISDN: Support DR6 indication in mISDNipac driver
  net: ratelimit warnings about dst entry refcount underflow or overflow
  bonding: Fix bonding crash
  tcp: take care of truncations done by sk_filter()
  tcp: fix wrong checksum calculation on MTU probing
  tcp: fix overflow in __tcp_retransmit_skb()
  tcp: properly scale window in tcp_v[46]_reqsk_send_ack()
  tcp: fix use after free in tcp_xmit_retransmit_queue()
  net/irda: handle iriap_register_lsap() allocation failure
  ip6_tunnel: disable caching when the traffic class is inherited
  ip6_tunnel: Clear IP6CB in ip6tunnel_xmit()
  ipv6: dccp: add missing bind_conflict to dccp_ipv6_mapped
  ipv6: dccp: fix out of bound access in dccp_v6_err()
  ipv6: correctly add local routes when lo goes up
  ip6_gre: fix flowi6_proto value in ip6gre_xmit_other()
  ipv6: fix rtnl locking in setsockopt for anycast and multicast
  ipv6: addrconf: fix dev refcont leak when DAD failed
  ipv6: move DAD and addrconf_verify processing to workqueue
  ipv6: split duplicate address detection and router solicitation timer
  ipv6: don't call fib6_run_gc() until routing is ready
  stddef.h: move offsetofend inside #ifndef/#endif guard, neaten
  include/stddef.h: Move offsetofend() from vfio.h to a generic kernel header
  drivers/vfio: Rework offsetofend()
  vt: clear selection before resizing
  tty: vt, fix bogus division in csi_J
  tty: limit terminal size to 4M chars
  tty: Prevent ldisc drivers from re-using stale tty fields
  perf: Tighten (and fix) the grouping condition
  perf symbols: Fixup symbol sizes before picking best ones
  mtd: nand: davinci: Reinitialize the HW ECC engine in 4bit hwctl
  mtd: pmcmsp-flash: Allocating too much in init_msp_flash()
  mtd: blkdevs: fix potential deadlock + lockdep warnings
  IB/cm: Mark stale CM id's whenever the mad agent was unregistered
  IB/uverbs: Fix leak of XRC target QPs
  IB/mlx4: Fix create CQ error flow
  IB/mlx4: Fix incorrect MC join state bit-masking on SR-IOV
  IB/ipoib: Don't allow MC joins during light MC flush
  IB/core: Fix use after free in send_leave function
  IB/ipoib: Fix memory corruption in ipoib cm mode connect flow
  EDAC: Increment correct counter in edac_inc_ue_error()
  timers: Use proper base migration in add_timer_on()
  cdc-acm: fix wrong pipe type on rx interrupt xfers
  thermal: hwmon: Properly report critical temperature in sysfs
  iio: accel: kxsd9: Fix scaling bug
  iio: accel: kxsd9: Fix raw read return
  i2c: at91: fix write transfers by clearing pending interrupt first
  i2c: core: fix NULL pointer dereference under race condition
  em28xx-i2c: rt_mutex_trylock() returns zero on failure
  i2c-eg20t: fix race between i2c init and interrupt enable
  hwrng: omap - Only fail if pm_runtime_get_sync returns < 0
  hwrng: omap - Fix assumption that runtime_get_sync will always succeed
  hwrng: exynos - Disable runtime PM on probe failure
  Input: ili210x - fix permissions on "calibrate" attribute
  Input: i8042 - set up shared ps2_cmd_mutex for AUX ports
  Input: i8042 - break load dependency between atkbd/psmouse and i8042
  qxl: check for kmap failures
  drm/radeon: Ensure vblank interrupt is enabled on DPMS transition to on
  drm: Reject page_flip for !DRIVER_MODESET
  drm/radeon: fix radeon_move_blit on 32bit systems
  driver core: fix race between creating/querying glue dir and its cleanup
  driver core: Delete an unnecessary check before the function call "put_device"
  hostfs: Freeing an ERR_PTR in hostfs_fill_sb_common()
  isofs: Do not return EACCES for unknown filesystems
  fs/super.c: fix race between freeze_super() and thaw_super()
  fs/seq_file: fix out-of-bounds read
  NFSv4: Open state recovery must account for file permission changes
  NFS: Don't drop CB requests with invalid principals
  NFSD: Using free_conn free connection
  NFSv4.x: Fix a refcount leak in nfs_callback_up_net
  UBI: fastmap: scrub PEB when bitflips are detected in a free PEB EC header
  ubifs: Fix regression in ubifs_readdir()
  ubifs: Abort readdir upon error
  UBIFS: Fix possible memory leak in ubifs_readdir()
  ubifs: Fix xattr_names length in exit paths
  ubifs: Fix assertion in layout_in_gaps()
  ocfs2: fix start offset to ocfs2_zero_range_for_truncate()
  ocfs2/dlm: fix race between convert and migration
  btrfs: ensure that file descriptor used with subvol ioctls is a dir
  libxfs: clean up _calc_dquots_per_chunk
  xfs: fix superblock inprogress check
  reiserfs: Unlock superblock before calling reiserfs_quota_on_mount()
  reiserfs: fix "new_insert_key may be used uninitialized ..."
  ext4: sanity check the block and cluster size at mount time
  ext4: allow DAX writeback for hole punch
  ext4: reinforce check of i_dtime when clearing high fields of uid and gid
  ext4: use __GFP_NOFAIL in ext4_free_blocks()
  ext4: avoid modifying checksum fields directly during checksum verification
  ext4: validate that metadata blocks do not overlap superblock
  scsi: arcmsr: Send SYNCHRONIZE_CACHE command to firmware
  scsi: scsi_debug: Fix memory leak if LBP enabled and module is unloaded
  scsi: arcmsr: Buffer overflow in arcmsr_iop_message_xfer()
  scsi: Fix use-after-free
  scsi: ibmvfc: Fix I/O hang when port is not mapped
  scsi: megaraid_sas: fix macro MEGASAS_IS_LOGICAL to avoid regression
  scsi: megaraid_sas: Fix data integrity failure for JBOD (passthrough) devices
  mpt2sas: Fix secure erase premature termination
  scsi: mpt3sas: fix hang on ata passthrough commands
  scsi: mpt3sas: Unblock device after controller reset
  scsi: mpt3sas: Fix secure erase premature termination
  scsi: zfcp: spin_lock_irqsave() is not nestable
  zfcp: trace full payload of all SAN records (req,resp,iels)
  zfcp: fix payload trace length for SAN request&response
  zfcp: fix D_ID field with actual value on tracing SAN responses
  zfcp: restore tracing of handle for port and LUN with HBA records
  zfcp: trace on request for open and close of WKA port
  zfcp: restore: Dont use 0 to indicate invalid LUN in rec trace
  zfcp: retain trace level for SCSI and HBA FSF response records
  zfcp: close window with unblocked rport during rport gone
  zfcp: fix ELS/GS request&response length for hardware data router
  zfcp: fix fc_host port_type with NPIV
  ALSA: pcm : Call kill_fasync() in stream lock
  ALSA: ali5451: Fix out-of-bound position reporting
  ALSA: timer: fix NULL pointer dereference on memory allocation failure
  ALSA: timer: fix division by zero after SNDRV_TIMER_IOCTL_CONTINUE
  ALSA: timer: fix NULL pointer dereference in read()/ioctl() race
  ALSA: rawmidi: Fix possible deadlock with virmidi registration
  Fix USB CB/CBI storage devices with CONFIG_VMAP_STACK=y
  usb: chipidea: move the lock initialization to core file
  usb: gadget: u_ether: remove interrupt throttling
  USB: serial: cp210x: fix tiocmget error handling
  usb: gadget: function: u_ether: don't starve tx request queue
  usb: misc: legousbtower: Fix NULL pointer deference
  USB: serial: cp210x: fix hardware flow-control disable
  usb: gadget: fsl_qe_udc: signedness bug in qe_get_frame()
  USB: change bInterval default to 10 ms
  usb: renesas_usbhs: fix clearing the {BRDY,BEMP}STS condition
  USB: serial: mos7840: fix non-atomic allocation in write path
  USB: serial: mos7720: fix non-atomic allocation in write path
  USB: kobil_sct: fix non-atomic allocation in write path
  USB: serial: fix memleak in driver-registration error path
  usb: xhci: Fix panic if disconnect
  USB: fix typo in wMaxPacketSize validation
  USB: validate wMaxPacketValue entries in endpoint descriptors
  usb: dwc3: gadget: increment request->actual once
  coredump: fix unfreezable coredumping task
  swapfile: fix memory corruption via malformed swapfile
  Fix potential infoleak in older kernels
  arc: don't leak bits of kernel stack into coredump
  fix memory leaks in tracing_buffers_splice_read()
  fix fault_in_multipages_...() on architectures with no-op access_ok()
  ia64: copy_from_user() should zero the destination on access_ok() failure
  ppc32: fix copy_from_user()
  sparc32: fix copy_from_user()
  mn10300: copy_from_user() should zero on access_ok() failure...
  openrisc: fix the fix of copy_from_user()
  openrisc: fix copy_from_user()
  parisc: fix copy_from_user()
  metag: copy_from_user() should zero the destination on access_ok() failure
  alpha: fix copy_from_user()
  asm-generic: make copy_from_user() zero the destination properly
  mips: copy_from_user() must zero the destination on access_ok() failure
  hexagon: fix strncpy_from_user() error return
  sh: fix copy_from_user()
  score: fix copy_from_user() and friends
  blackfin: fix copy_from_user()
  cris: buggered copy_from_user/copy_to_user/clear_user
  frv: fix clear_user()
  asm-generic: make get_user() clear the destination on errors
  ARC: uaccess: get_user to zero out dest in cause of fault
  s390: get_user() should zero on failure
  score: fix __get_user/get_user
  sh64: failing __get_user() should zero
  m32r: fix __get_user()
  mn10300: failing __get_user() and get_user() should zero
  microblaze: fix copy_from_user()
  microblaze: fix __get_user()
  parisc: Ensure consistent state when switching to kernel stack at syscall entry
  s390/dasd: fix hanging device after clear subchannel
  avr32: off by one in at32_init_pio()
  avr32: fix 'undefined reference to `___copy_from_user'
  avr32: fix copy_from_user()
  powerpc/nvram: Fix an incorrect partition merge
  powerpc/64: Fix incorrect return value from __copy_tofrom_user
  powerpc/powernv: Use CPU-endian PEST in pnv_pci_dump_p7ioc_diag_data()
  powerpc/vdso64: Use double word compare on pointers
  powerpc/mm: Don't alias user region to other regions below PAGE_OFFSET
  MIPS: ptrace: Fix regs_return_value for kernel context
  MIPS: Malta: Fix IOCU disable switch read for MIPS64
  arm64: debug: avoid resetting stepping state machine when TIF_SINGLESTEP
  arm64: spinlocks: implement smp_mb__before_spinlock() as smp_mb()
  arm64: Define AT_VECTOR_SIZE_ARCH for ARCH_DLINFO
  arm64: avoid returning from bad_mode
  ARM: sa1111: fix pcmcia suspend/resume
  ARM: sa1100: clear reset status prior to reboot
  ARM: 8618/1: decompressor: reset ttbcr fields to use TTBR0 on ARMv7
  ARM: 8616/1: dt: Respect property size when parsing CPUs
  iommu/amd: Free domain id when free a domain of struct dma_ops_domain
  iommu/amd: Update Alias-DTE in update_device_table()
  x86/um: reuse asm-generic/barrier.h
  x86/build: Build compressed x86 kernels as PIE
  x86/paravirt: Do not trace _paravirt_ident_*() functions
  x86/mm/pat, /dev/mem: Remove superfluous error message
  x86/apic: Do not init irq remapping if ioapic is disabled
  x86/mm: Disable preemption during CR3 read+write
  x86/traps: Ignore high word of regs->cs in early_idt_handler_common
  x86/xen: fix upper bound of pmd loop in xen_cleanhighmap()
  xen-pciback: Add name prefix to global 'permissive' variable
  xen/pciback: Don't allow MSI-X ops if PCI_COMMAND_MEMORY is not set.
  xen/pciback: For XEN_PCI_OP_disable_msi[|x] only disable if device has MSI(X) enabled.
  xen/pciback: Do not install an IRQ handler for MSI interrupts.
  xen/pciback: Return error on XEN_PCI_OP_enable_msix when device has MSI or MSI-X enabled
  xen/pciback: Return error on XEN_PCI_OP_enable_msi when device has MSI or MSI-X enabled
  xen/pciback: Save the number of MSI-X entries to be copied later.
  xen/pciback: Save xen_pci_op commands before processing it
  xen-blkback: only read request operation from shared ring once
  xen-netback: use RING_COPY_REQUEST() throughout
  xen-netback: don't use last request to determine minimum Tx credit
  xen: Add RING_COPY_REQUEST()
  x86/mm/xen: Suppress hugetlbfs in PV guests
  ppp: defer netns reference release for ppp channel
  PM / devfreq: Fix incorrect type issue.
  KVM: Disable irq while unregistering user notifier
  KVM: x86: fix missed SRCU usage in kvm_lapic_set_vapic_addr
  KVM: x86: fix wbinvd_dirty_mask use-after-free
  KVM: MIPS: Make ERET handle ERL before EXL
  KVM: nVMX: postpone VMCS changes on MSR_IA32_APICBASE write
  KVM: MIPS: Drop other CPU ASIDs on guest MMU changes
  KVM: MIPS: Precalculate MMIO load resume PC
  MIPS: KVM: Fix unused variable build warning
  crypto: gcm - Fix IV buffer size in crypto_gcm_setkey
  crypto: skcipher - Fix blkcipher walk OOM crash
  crypto: cryptd - initialize child shash_desc on import
  crypto: algif_skcipher - Load TX SG list after waiting
  crypto: algif_skcipher - Fix race condition in skcipher_check_key
  crypto: algif_hash - Fix race condition in hash_check_key
  crypto: af_alg - Forbid bind(2) when nokey child sockets are present
  crypto: algif_skcipher - Remove custom release parent function
  crypto: algif_hash - Remove custom release parent function
  crypto: af_alg - Allow af_af_alg_release_parent to be called on nokey path
  crypto: algif_skcipher - Add key check exception for cipher_null
  crypto: skcipher - Add crypto_skcipher_has_setkey
  crypto: algif_hash - Require setkey before accept(2)
  crypto: shash - Fix has_key setting
  crypto: hash - Add crypto_ahash_has_setkey
  crypto: algif_skcipher - Add nokey compatibility path
  crypto: af_alg - Add nokey compatibility path
  crypto: af_alg - Disallow bind/setkey/... after accept(2)
  crypto: algif_skcipher - Require setkey before accept(2)
  sched/core: Fix an SMP ordering race in try_to_wake_up() vs. schedule()
  sched/core: Fix a race between try_to_wake_up() and a woken up task

Signed-off-by: Rohit Vashisht <rohitv88cf@gmail.com>

 Conflicts:
	arch/arm/mach-sa1100/generic.c
	arch/arm64/kernel/traps.c
	crypto/blkcipher.c
	drivers/base/core.c
	drivers/devfreq/devfreq.c
	drivers/usb/dwc3/gadget.c
	drivers/usb/gadget/u_ether.c
	fs/ubifs/dir.c
	include/net/if_inet6.h
	lib/genalloc.c
	net/ipv6/addrconf.c
	net/ipv6/tcp_ipv6.c
	net/wireless/scan.c