wlan: Add size to nvtable hwCalValues
Add size of uint16 to the validation after subtracting
the calData size instead of before to resolve
compilation issue.

Change-Id: I4c4fa7ce6fb1fc805281df17ed47f75cfaf39272
CRs-Fixed: 2197382

Fixes the following build warning with GCC 6+:

drivers/staging/prima/CORE/VOSS/src/wlan_nv_template_builtin.c:590:10: error: initializer element is not computable at load time
          (((char *)&(nvDefaults.tables.hwCalValues.calData.psSlpTimeOvrHdxLNA5G) +
          ^
drivers/staging/prima/CORE/VOSS/src/wlan_nv_template_builtin.c:590:10: note: (near initialization for ‘NvTablesBuiltIn[4][3].offset’)

Signed-off-by: Rohit Vashisht <rohitv88cf@gmail.com>